# index:
#    path: /
#    controller: App\Controller\DefaultController::helloMessage

hello:
    path: /hello-world
    controller: App\Controller\HelloWorldController::helloMessage

hello-view:
    path: /hello-world-view
    controller: App\Controller\HelloWorldController::helloMessageView

# test:
#     path: /hello-world-view
#     controller: App\Controller\HelloWorldController::helloMessageView
